export const Constants = {
  allCountry: [
    {
      name: "Africa",
      code: "002",
      category: "EMEA",
      children: [
        { name: "DZ", code: 0 },
        { name: "EG", code: 0 },
        { name: "EH", code: 0 },
        { name: "LY", code: 0 },
        { name: "MA", code: 0 },
        { name: "SD", code: 0 },
        { name: "SS", code: 0 },
        { name: "TN", code: 0 },
        { name: "BF", code: 0 },
        { name: "BJ", code: 0 },
        { name: "CI", code: 0 },
        { name: "CV", code: 0 },
        { name: "GH", code: 0 },
        { name: "GM", code: 0 },
        { name: "GN", code: 0 },
        { name: "GW", code: 0 },
        { name: "LR", code: 0 },
        { name: "ML", code: 0 },
        { name: "MR", code: 0 },
        { name: "NE", code: 0 },
        { name: "NG", code: 0 },
        { name: "SH", code: 0 },
        { name: "SL", code: 0 },
        { name: "SN", code: 0 },
        { name: "TG", code: 0 },
        { name: "AO", code: 0 },
        { name: "CD", code: 0 },
        { name: "ZR", code: 0 },
        { name: "CF", code: 0 },
        { name: "CG", code: 0 },
        { name: "CM", code: 0 },
        { name: "GA", code: 0 },
        { name: "GQ", code: 0 },
        { name: "ST", code: 0 },
        { name: "TD", code: 0 },
        { name: "BI", code: 0 },
        { name: "DJ", code: 0 },
        { name: "ER", code: 0 },
        { name: "ET", code: 0 },
        { name: "KE", code: 0 },
        { name: "KM", code: 0 },
        { name: "MG", code: 0 },
        { name: "MU", code: 0 },
        { name: "MW", code: 0 },
        { name: "MZ", code: 0 },
        { name: "RE", code: 0 },
        { name: "RW", code: 0 },
        { name: "SC", code: 0 },
        { name: "SO", code: 0 },
        { name: "TZ", code: 0 },
        { name: "UG", code: 0 },
        { name: "YT", code: 0 },
        { name: "ZM", code: 0 },
        { name: "ZW", code: 0 },
        { name: "BW", code: 0 },
        { name: "LS", code: 0 },
        { name: "NA", code: 0 },
        { name: "SZ", code: 0 },
        { name: "ZA", code: 0 },
      ],
    },
    {
      name: "Europe",
      code: "150",
      category: "EMEA",
      children: [
        { name: "GG", code: 0 },
        { name: "JE", code: 0 },
        { name: "AX", code: 0 },
        { name: "DK", code: 0 },
        { name: "EE", code: 0 },
        { name: "FI", code: 0 },
        { name: "FO", code: 0 },
        { name: "GB", code: 0 },
        { name: "IE", code: 0 },
        { name: "IM", code: 0 },
        { name: "IS", code: 0 },
        { name: "LT", code: 0 },
        { name: "LV", code: 0 },
        { name: "NO", code: 0 },
        { name: "SE", code: 0 },
        { name: "SJ", code: 0 },
        { name: "AT", code: 0 },
        { name: "BE", code: 0 },
        { name: "CH", code: 0 },
        { name: "DE", code: 0 },
        { name: "DD", code: 0 },
        { name: "FR", code: 0 },
        { name: "FX", code: 0 },
        { name: "LI", code: 0 },
        { name: "LU", code: 0 },
        { name: "MC", code: 0 },
        { name: "NL", code: 0 },
        { name: "BG", code: 0 },
        { name: "BY", code: 0 },
        { name: "CZ", code: 0 },
        { name: "HU", code: 0 },
        { name: "MD", code: 0 },
        { name: "PL", code: 0 },
        { name: "RO", code: 0 },
        { name: "RU", code: 0 },
        { name: "SU", code: 0 },
        { name: "SK", code: 0 },
        { name: "UA", code: 0 },
        { name: "AD", code: 0 },
        { name: "AL", code: 0 },
        { name: "BA", code: 0 },
        { name: "ES", code: 0 },
        { name: "GI", code: 0 },
        { name: "GR", code: 0 },
        { name: "HR", code: 0 },
        { name: "IT", code: 0 },
        { name: "ME", code: 0 },
        { name: "MK", code: 0 },
        { name: "MT", code: 0 },
        { name: "RS", code: 0 },
        { name: "PT", code: 0 },
        { name: "SI", code: 0 },
        { name: "SM", code: 0 },
        { name: "VA", code: 0 },
        { name: "YU", code: 0 },
      ],
    },
    {
      name: "Americas",
      category: "Americas",
      code: "019",
      children: [
        { name: "BM", code: 0 },
        { name: "CA", code: 0 },
        { name: "GL", code: 0 },
        { name: "PM", code: 0 },
        { name: "US", code: 0 },
        { name: "AG", code: 0 },
        { name: "AI", code: 0 },
        { name: "AN", code: 0 },
        { name: "AW", code: 0 },
        { name: "BB", code: 0 },
        { name: "BL", code: 0 },
        { name: "BS", code: 0 },
        { name: "CU", code: 0 },
        { name: "DM", code: 0 },
        { name: "DO", code: 0 },
        { name: "GD", code: 0 },
        { name: "GP", code: 0 },
        { name: "HT", code: 0 },
        { name: "JM", code: 0 },
        { name: "KN", code: 0 },
        { name: "KY", code: 0 },
        { name: "LC", code: 0 },
        { name: "MF", code: 0 },
        { name: "MQ", code: 0 },
        { name: "MS", code: 0 },
        { name: "PR", code: 0 },
        { name: "TC", code: 0 },
        { name: "TT", code: 0 },
        { name: "VC", code: 0 },
        { name: "VG", code: 0 },
        { name: "VI", code: 0 },
        { name: "BZ", code: 0 },
        { name: "CR", code: 0 },
        { name: "GT", code: 0 },
        { name: "HN", code: 0 },
        { name: "MX", code: 0 },
        { name: "NI", code: 0 },
        { name: "PA", code: 0 },
        { name: "SV", code: 0 },
        { name: "AR", code: 0 },
        { name: "BO", code: 0 },
        { name: "BR", code: 0 },
        { name: "CL", code: 0 },
        { name: "CO", code: 0 },
        { name: "EC", code: 0 },
        { name: "FK", code: 0 },
        { name: "GF", code: 0 },
        { name: "GY", code: 0 },
        { name: "PE", code: 0 },
        { name: "PY", code: 0 },
        { name: "SR", code: 0 },
        { name: "UY", code: 0 },
        { name: "VE", code: 0 },
      ],
    },
    {
      name: "Asia",
      code: "142",
      category: "APAC",
      children: [
        { name: "TM", code: 0 },
        { name: "TJ", code: 0 },
        { name: "KG", code: 0 },
        { name: "KZ", code: 0 },
        { name: "UZ", code: 0 },
        { name: "CN", code: 0 },
        { name: "HK", code: 0 },
        { name: "JP", code: 0 },
        { name: "KP", code: 0 },
        { name: "KR", code: 0 },
        { name: "MN", code: 0 },
        { name: "MO", code: 0 },
        { name: "TW", code: 0 },
        { name: "AF", code: 0 },
        { name: "BD", code: 0 },
        { name: "BT", code: 0 },
        { name: "IN", code: 0 },
        { name: "IR", code: 0 },
        { name: "LK", code: 0 },
        { name: "MV", code: 0 },
        { name: "NP", code: 0 },
        { name: "PK", code: 0 },
        { name: "BN", code: 0 },
        { name: "ID", code: 0 },
        { name: "KH", code: 0 },
        { name: "LA", code: 0 },
        { name: "MM", code: 0 },
        { name: "BU", code: 0 },
        { name: "MY", code: 0 },
        { name: "PH", code: 0 },
        { name: "SG", code: 0 },
        { name: "TH", code: 0 },
        { name: "TL", code: 0 },
        { name: "TP", code: 0 },
        { name: "VN", code: 0 },
        { name: "AE", code: 0 },
        { name: "AM", code: 0 },
        { name: "AZ", code: 0 },
        { name: "BH", code: 0 },
        { name: "CY", code: 0 },
        { name: "GE", code: 0 },
        { name: "IL", code: 0 },
        { name: "IQ", code: 0 },
        { name: "JO", code: 0 },
        { name: "KW", code: 0 },
        { name: "LB", code: 0 },
        { name: "OM", code: 0 },
        { name: "PS", code: 0 },
        { name: "QA", code: 0 },
        { name: "SA", code: 0 },
        { name: "NT", code: 0 },
        { name: "SY", code: 0 },
        { name: "TR", code: 0 },
        { name: "YE", code: 0 },
        { name: "YD", code: 0 },
      ],
    },
    {
      name: "Oceania",
      code: "009",
      category: "APAC",
      children: [
        { name: "AU", code: 0 },
        { name: "NF", code: 0 },
        { name: "NZ", code: 0 },
        { name: "FJ", code: 0 },
        { name: "NC", code: 0 },
        { name: "PG", code: 0 },
        { name: "SB", code: 0 },
        { name: "VU", code: 0 },
        { name: "FM", code: 0 },
        { name: "GU", code: 0 },
        { name: "KI", code: 0 },
        { name: "MH", code: 0 },
        { name: "MP", code: 0 },
        { name: "NR", code: 0 },
        { name: "PW", code: 0 },
        { name: "AS", code: 0 },
        { name: "CK", code: 0 },
        { name: "NU", code: 0 },
        { name: "PF", code: 0 },
        { name: "PN", code: 0 },
        { name: "TK", code: 0 },
        { name: "TO", code: 0 },
        { name: "TV", code: 0 },
        { name: "WF", code: 0 },
        { name: "WS", code: 0 },
      ],
    },
  ],
};


export enum ScoutSwitchType {
  index = "Index",
  quickBridge = "QuickBridge",
  bidder = "Bidder"
}

export enum QuickBridgeTabType {
  vehile = "Vehicle",
  oem = "OEM",
  class = "Class",
  segment = "Segment",
  technology = "Technology",
  commodity = "Commodity",
  productionTech = "Production Tech",
  services = "3P Services",
  pioneer = "Pioneer",
}
