
export const allCountry = [
  {
    name: "Africa",
    code: "002",
    category: "EMEA",
    categoryId: 3,
    children: [
    { name: "DZ", code: 0, fullName: "Algeria" },
    { name: "AO", code: 0, fullName: "Angola" },
    { name: "BJ", code: 0, fullName: "Benin" },
    { name: "BW", code: 0, fullName: "Botswana" },

    { name: "BF", code: 0, fullName: "Burkina Faso" },
    { name: "BI", code: 0, fullName: "Burundi" },
    { name: "CM", code: 0, fullName: "Cameroon" },
    { name: "TD", code: 0, fullName: "Chad" },
    { name: "DJ", code: 0, fullName: "Djibouti" },

    { name: "EG", code: 0, fullName: "Egypt" },
    { name: "GQ", code: 0, fullName: "Equatorial Guinea" },
    { name: "ER", code: 0, fullName: "Eritrea" },
    { name: "ET", code: 0, fullName: "Ethiopia" },
    { name: "GA", code: 0, fullName: "Gabon" },
    { name: "GH", code: 0, fullName: "Ghana" },

    { name: "GN", code: 0, fullName: "Guinea" },
    { name: "GW", code: 0, fullName: "Guinea-Bissau" },
    { name: "KE", code: 0, fullName: "Kenya" },
    { name: "LS", code: 0, fullName: "Lesotho" },
    { name: "LR", code: 0, fullName: "Liberia" },

    { name: "LY", code: 0, fullName: "Libya" },
    { name: "MG", code: 0, fullName: "Madagascar" },
    { name: "MW", code: 0, fullName: "Malawi" },
    { name: "ML", code: 0, fullName: "Mali" },
    { name: "MR", code: 0, fullName: "Mauritania" },
    { name: "YT", code: 0, fullName: "Mayotte" },
    { name: "MA", code: 0, fullName: "Morocco" },
    { name: "MZ", code: 0, fullName: "Mozambique" },
    { name: "NA", code: 0, fullName: "Namibia" },
    { name: "NE", code: 0, fullName: "Niger" },
    { name: "NG", code: 0, fullName: "Nigeria" },

    { name: "RW", code: 0, fullName: "Rwanda" },
    { name: "ST", code: 0, fullName: "Sao Tome and Principe" },
    { name: "SN", code: 0, fullName: "Senegal" },

    { name: "SL", code: 0, fullName: "Sierra Leone" },
    { name: "SO", code: 0, fullName: "Somalia" },
    { name: "ZA", code: 0, fullName: "South Africa" },

    { name: "SS", code: 0, fullName: "South Sudan" },
    { name: "TG", code: 0, fullName: "Togo" },
    { name: "TN", code: 0, fullName: "Tunisia" },

    { name: "UG", code: 0, fullName: "Uganda" },
    { name: "EH", code: 0, fullName: "Western Sahara" },
    { name: "ZM", code: 0, fullName: "Zambia" },

    { name: "ZW", code: 0, fullName: "Zimbabwe" }
    ],
  },
  {
    name: "Europe",
    code: "150",
    category: "EMEA",
    categoryId: 3,
    children: [
      { name: "GL", code: 0, fullName: "Greenland" },
      { name: "AL", code: 0, fullName: "Albania" },
      { name: "CY", code: 0, fullName: "Cyprus" },
      { name: "AD", code: 0, fullName: "Andorra" },
      { name: "AT", code: 0, fullName: "Austria" },
      { name: "BY", code: 0, fullName: "Belarus" },
      { name: "BE", code: 0, fullName: "Belgium" },

      { name: "BIH", code: 0, fullName: "Bosnia and Herzegovina" },
      { name: "BG", code: 0, fullName: "Bulgaria" },
      { name: "HR", code: 0, fullName: "Croatia" },
      { name: "CZ", code: 0, fullName: "Czech Republic" },
      { name: "DK", code: 0, fullName: "Denmark" },
      { name: "EST", code: 0, fullName: "Estonia" },
      { name: "FIN", code: 0, fullName: "Finland" },

      { name: "FR", code: 0, fullName: "France" },
      { name: "DE", code: 0, fullName: "Germany" },
      { name: "GI", code: 0, fullName: "Gibraltar" },
      { name: "GR", code: 0, fullName: "Greece" },
      { name: "HU", code: 0, fullName: "Hungary" },
      { name: "IS", code: 0, fullName: "Iceland" },
      { name: "IE", code: 0, fullName: "Ireland" },
      { name: "IT", code: 0, fullName: "Italy" },
      { name: "RKS", code: 0, fullName: "Kosovo" },

      { name: "LV", code: 0, fullName: "Latvia" },
      { name: "LI", code: 0, fullName: "Liechtenstein" },
      { name: "LT", code: 0, fullName: "Lithuania" },
      { name: "LU", code: 0, fullName: "Luxembourg" },
      { name: "MT", code: 0, fullName: "Malta" },
      { name: "MD", code: 0, fullName: "Republic of Moldova" },

      { name: "MC", code: 0, fullName: "Monaco" },
      { name: "ME", code: 0, fullName: "Montenegro" },
      { name: "NL", code: 0, fullName: "Netherlands" },
      { name: "NMK", code: 0, fullName: "North Macedonia" },
      { name: "NO", code: 0, fullName: "Norway" },
      { name: "PL", code: 0, fullName: "Poland" },

      { name: "PT", code: 0, fullName: "Portugal" },
      { name: "RO", code: 0, fullName: "Romania" },
      { name: "SM", code: 0, fullName: "San Marino" },
      { name: "RS", code: 0, fullName: "Serbia" },
      { name: "SK", code: 0, fullName: "Slovakia (Slovak Republic)" },
      { name: "SI", code: 0, fullName: "Slovenia" },


      { name: "ES", code: 0, fullName: "Spain" },
      { name: "SE", code: 0, fullName: "Sweden" },
      { name: "CH", code: 0, fullName: "Switzerland" },
      { name: "UA", code: 0, fullName: "Ukraine" },
      { name: "GB", code: 0, fullName: "United Kingdom" },
    ],
  },
  {
    name: "Americas",
    category: "Americas",
    categoryId: 2,
    code: "019",
    children: [
      { name: "AS", code: 0, fullName: "American Samoa" },
      { name: "AI", code: 0, fullName: "Anguilla" },
      { name: "AG", code: 0, fullName: "Antigua and Barbuda" },
      { name: "AR", code: 0, fullName: "Argentina" },
      { name: "AW", code: 0, fullName: "Aruba" },
      { name: "BS", code: 0, fullName: "Bahamas" },
      { name: "BB", code: 0, fullName: "Barbados" },


      { name: "BZ", code: 0, fullName: "Belize" },
      { name: "BM", code: 0, fullName: "Bermuda" },
      { name: "BO", code: 0, fullName: "Bolivia" },
      { name: "BR", code: 0, fullName: "Brazil" },
      { name: "CA", code: 0, fullName: "Canada" },
      { name: "KY", code: 0, fullName: "Cayman Islands" },
      { name: "CL", code: 0, fullName: "Chile" },

      { name: "CO", code: 0, fullName: "Colombia" },
      { name: "CR", code: 0, fullName: "Costa Rica" },
      { name: "CU", code: 0, fullName: "Cuba" },
      { name: "DM", code: 0, fullName: "Dominica" },
      { name: "DO", code: 0, fullName: "Dominican Republic" },
      { name: "EC", code: 0, fullName: "Ecuador" },
      { name: "SV", code: 0, fullName: "El Salvador" },
      { name: "GF", code: 0, fullName: "French Guiana" },

      { name: "GD", code: 0, fullName: "Grenada" },
      { name: "GP", code: 0, fullName: "Guadeloupe" },
      { name: "GT", code: 0, fullName: "Guatemala" },
      { name: "GY", code: 0, fullName: "Guyana" },
      { name: "HT", code: 0, fullName: "Haiti" },
      { name: "HN", code: 0, fullName: "Honduras" },


      { name: "JM", code: 0, fullName: "Jamaica" },
      { name: "MQ", code: 0, fullName: "Martinique" },
      { name: "MX", code: 0, fullName: "Mexico" },
      { name: "MS", code: 0, fullName: "Montserrat" },
      { name: "NI", code: 0, fullName: "Nicaragua" },

      { name: "PA", code: 0, fullName: "Panama" },

      { name: "PY", code: 0, fullName: "Paraguay" },
      { name: "PE", code: 0, fullName: "Peru" },
      { name: "PR", code: 0, fullName: "Puerto Rico" },
      { name: "KN", code: 0, fullName: "Saint Kitts and Nevis" },
      { name: "LC", code: 0, fullName: "Saint Lucia" },
      { name: "VC", code: 0, fullName: "Saint Vincent and the Grenadines" },
      { name: "SR", code: 0, fullName: "Suriname" },
      { name: "TT", code: 0, fullName: "Trinidad and Tobago" },
      { name: "US", code: 0, fullName: "United States" },
      { name: "UY", code: 0, fullName: "Uruguay" },
      { name: "VE", code: 0, fullName: "Venezuela" },

      { name: "VG", code: 0, fullName: "Virgin Islands (British)" },
      { name: "VI", code: 0, fullName: "Virgin Islands (U.S.)" }
    ],
  },
  {
    name: "Asia",
    code: "142",
    category: "APAC",
    categoryId: 1,
    children: [
      { name: "MU", code: 0, fullName: "Mauritius" },
      { name: "SC", code: 0, fullName: "Seychelles" },
      { name: "AF", code: 0, fullName: "Afghanistan" },
      { name: "AM", code: 0, fullName: "Armenia" },
      { name: "AZ", code: 0, fullName: "Azerbaijan" },

      { name: "BH", code: 0, fullName: "Bahrain" },
      { name: "BD", code: 0, fullName: "Bangladesh" },
      { name: "BT", code: 0, fullName: "Bhutan" },
      { name: "BN", code: 0, fullName: "Brunei Darussalam" },
      { name: "KH", code: 0, fullName: "Cambodia" },
      { name: "CN", code: 0, fullName: "China" },

      { name: "CX", code: 0, fullName: "Christmas Island" },
      { name: "GE", code: 0, fullName: "Georgia" },
      { name: "HK", code: 0, fullName: "Hong Kong" },
      { name: "IN", code: 0, fullName: "India" },
      { name: "ID", code: 0, fullName: "Indonesia" },

      { name: "IR", code: 0, fullName: "Iran" },
      { name: "IQ", code: 0, fullName: "Iraq" },
      { name: "IL", code: 0, fullName: "Israel" },
      { name: "JP", code: 0, fullName: "Japan" },
      { name: "JO", code: 0, fullName: "Jordan" },

      { name: "KZ", code: 0, fullName: "Kazakhstan" },
      { name: "KP", code: 0, fullName: "Korea, Democratic People's Rep. (North Korea)" },
      { name: "KR", code: 0, fullName: "Korea, Republic of (South Korea)" },
      { name: "KW", code: 0, fullName: "Kuwait" },
      { name: "KG", code: 0, fullName: "Kyrgyzstan" },

      { name: "LA", code: 0, fullName: "Lao, People''s Democratic Republic" },
      { name: "LB", code: 0, fullName: "Lebanon" },
      { name: "MO", code: 0, fullName: "Macau" },
      { name: "MY", code: 0, fullName: "Malaysia" },
      { name: "MV", code: 0, fullName: "Maldives" },

      { name: "MN", code: 0, fullName: "Mongolia" },
      { name: "MM", code: 0, fullName: "Myanmar, Burma" },
      { name: "NP", code: 0, fullName: "Nepal" },
      { name: "NZ", code: 0, fullName: "New Zealand" },
      { name: "OM", code: 0, fullName: "Oman" },

      { name: "PK", code: 0, fullName: "Pakistan" },
      { name: "PG", code: 0, fullName: "Papua New Guinea" },
      { name: "PH", code: 0, fullName: "Philippines" },
      { name: "QA", code: 0, fullName: "Qatar" },
      { name: "RU", code: 0, fullName: "Russian Federation" },

      { name: "SA", code: 0, fullName: "Saudi Arabia" },
      { name: "SG", code: 0, fullName: "Singapore" },
      { name: "LK", code: 0, fullName: "Sri Lanka" },
      { name: "TW", code: 0, fullName: "Taiwan" },
      { name: "TJ", code: 0, fullName: "Tajikistan" },

      { name: "TH", code: 0, fullName: "Thailand" },
      { name: "TK", code: 0, fullName: "Tokelau" },
      { name: "TR", code: 0, fullName: "Turkey" },
      { name: "TM", code: 0, fullName: "Turkmenistan" },
      { name: "AE", code: 0, fullName: "United Arab Emirates" },

      { name: "UZ", code: 0, fullName: "Uzbekistan" },
      { name: "VN", code: 0, fullName: "Vietnam" },
      { name: "YE", code: 0, fullName: "Yemen" }
    ],
  },
  {
    name: "Oceania",
    code: "009",
    category: "APAC",
    categoryId: 1,
    children: [
      { name: "AU", code: 0, fullName: "Australia" }
    ],
  },
];


// export const allCountry = [
//   {
//     name: "Africa",
//     code: "002",
//     category: "EMEA",
//     categoryId: 3,
//     children: [
//       // { name: "DZ", code: 0 },
//       { name: "EG", code: 0 },
//       // { name: "EH", code: 0 },
//       // { name: "LY", code: 0 },
//       { name: "MA", code: 0 },
//       // { name: "SD", code: 0 },
//       // { name: "SS", code: 0 },
//       { name: "TN", code: 0 },
//       // { name: "BF", code: 0 },
//       // { name: "BJ", code: 0 },
//       // { name: "CI", code: 0 },
//       // { name: "CV", code: 0 },
//       // { name: "GH", code: 0 },
//       // { name: "GM", code: 0 },
//       // { name: "GN", code: 0 },
//       // { name: "GW", code: 0 },
//       // { name: "LR", code: 0 },
//       // { name: "ML", code: 0 },
//       // { name: "MR", code: 0 },
//       // { name: "NE", code: 0 },
//       // { name: "NG", code: 0 },
//       // { name: "SH", code: 0 },
//       // { name: "SL", code: 0 },
//       // { name: "SN", code: 0 },
//       // { name: "TG", code: 0 },
//       // { name: "AO", code: 0 },
//       // { name: "CD", code: 0 },
//       // { name: "ZR", code: 0 },
//       // { name: "CF", code: 0 },
//       // { name: "CG", code: 0 },
//       // { name: "CM", code: 0 },
//       // { name: "GA", code: 0 },
//       // { name: "GQ", code: 0 },
//       // { name: "ST", code: 0 },
//       // { name: "TD", code: 0 },
//       // { name: "BI", code: 0 },
//       // { name: "DJ", code: 0 },
//       // { name: "ER", code: 0 },
//       // { name: "ET", code: 0 },
//       // { name: "KE", code: 0 },
//       // { name: "KM", code: 0 },
//       // { name: "MG", code: 0 },
//       // { name: "MU", code: 0 },
//       // { name: "MW", code: 0 },
//       // { name: "MZ", code: 0 },
//       // { name: "RE", code: 0 },
//       // { name: "RW", code: 0 },
//       // { name: "SC", code: 0 },
//       // { name: "SO", code: 0 },
//       // { name: "TZ", code: 0 },
//       // { name: "UG", code: 0 },
//       // { name: "YT", code: 0 },
//       // { name: "ZM", code: 0 },
//       // { name: "ZW", code: 0 },
//       // { name: "BW", code: 0 },
//       // { name: "LS", code: 0 },
//       // { name: "NA", code: 0 },
//       // { name: "SZ", code: 0 },
//       { name: "ZA", code: 0 },
//     ],
//   },
//   {
//     name: "Europe",
//     code: "150",
//     category: "EMEA",
//     categoryId: 3,
//     children: [
//       // { name: "GG", code: 0 },
//       // { name: "JE", code: 0 },
//       // { name: "AX", code: 0 },
//       { name: "DK", code: 0 },
//       // { name: "EE", code: 0 },
//       { name: "FI", code: 0 },
//       // { name: "FO", code: 0 },
//       { name: "GB", code: 0 },
//       { name: "IE", code: 0 },
//       // { name: "IM", code: 0 },
//       // { name: "IS", code: 0 },
//       // { name: "LT", code: 0 },
//       // { name: "LV", code: 0 },
//       { name: "NO", code: 0 },
//       { name: "SE", code: 0 },
//       // { name: "SJ", code: 0 },
//       // { name: "AT", code: 0 },
//       // { name: "BE", code: 0 },
//       { name: "CH", code: 0 },
//       { name: "DE", code: 0 },
//       // { name: "DD", code: 0 },
//       { name: "FR", code: 0 },
//       // { name: "FX", code: 0 },
//       // { name: "LI", code: 0 },
//       { name: "LU", code: 0 },
//       // { name: "MC", code: 0 },
//       { name: "NL", code: 0 },
//       // { name: "BG", code: 0 },
//       // { name: "BY", code: 0 },
//       { name: "CZ", code: 0 },
//       { name: "HU", code: 0 },
//       // { name: "MD", code: 0 },
//       { name: "PL", code: 0 },
//       { name: "RO", code: 0 },
//       { name: "RU", code: 0 },
//       // { name: "SU", code: 0 },
//       { name: "SK", code: 0 },
//       // { name: "UA", code: 0 },
//       // { name: "AD", code: 0 },
//       // { name: "AL", code: 0 },
//       // { name: "BA", code: 0 },
//       { name: "ES", code: 0 },
//       // { name: "GI", code: 0 },
//       // { name: "GR", code: 0 },
//       { name: "HR", code: 0 },
//       { name: "IT", code: 0 },
//       // { name: "ME", code: 0 },
//       // { name: "MK", code: 0 },
//       { name: "MT", code: 0 },
//       // { name: "RS", code: 0 },
//       { name: "PT", code: 0 },
//       { name: "SI", code: 0 },
//       // { name: "SM", code: 0 },
//       // { name: "VA", code: 0 },
//       // { name: "YU", code: 0 },
//     ],
//   },
//   {
//     name: "Americas",
//     category: "Americas",
//     categoryId: 2,
//     code: "019",
//     children: [
//       // { name: "BM", code: 0 },
//       { name: "CA", code: 0 },
//       // { name: "GL", code: 0 },
//       // { name: "PM", code: 0 },
//       { name: "US", code: 0 },
//       // { name: "AG", code: 0 },
//       // { name: "AI", code: 0 },
//       // { name: "AN", code: 0 },
//       // { name: "AW", code: 0 },
//       // { name: "BB", code: 0 },
//       // { name: "BL", code: 0 },
//       // { name: "BS", code: 0 },
//       // { name: "CU", code: 0 },
//       // { name: "DM", code: 0 },
//       // { name: "DO", code: 0 },
//       // { name: "GD", code: 0 },
//       // { name: "GP", code: 0 },
//       // { name: "HT", code: 0 },
//       // { name: "JM", code: 0 },
//       // { name: "KN", code: 0 },
//       // { name: "KY", code: 0 },
//       // { name: "LC", code: 0 },
//       // { name: "MF", code: 0 },
//       // { name: "MQ", code: 0 },
//       // { name: "MS", code: 0 },
//       // { name: "PR", code: 0 },
//       // { name: "TC", code: 0 },
//       // { name: "TT", code: 0 },
//       // { name: "VC", code: 0 },
//       // { name: "VG", code: 0 },
//       // { name: "VI", code: 0 },
//       // { name: "BZ", code: 0 },
//       // { name: "CR", code: 0 },
//       // { name: "GT", code: 0 },
//       // { name: "HN", code: 0 },
//       // // { name: "MX", code: 0 },
//       // { name: "NI", code: 0 },
//       // { name: "PA", code: 0 },
//       // { name: "SV", code: 0 },
//       // { name: "AR", code: 0 },
//       // { name: "BO", code: 0 },
//       // { name: "BR", code: 0 },
//       // { name: "CL", code: 0 },
//       // { name: "CO", code: 0 },
//       // { name: "EC", code: 0 },
//       // { name: "FK", code: 0 },
//       // { name: "GF", code: 0 },
//       // { name: "GY", code: 0 },
//       // { name: "PE", code: 0 },
//       // { name: "PY", code: 0 },
//       // { name: "SR", code: 0 },
//       // { name: "UY", code: 0 },
//       // { name: "VE", code: 0 },
//     ],
//   },
//   {
//     name: "Asia",
//     code: "142",
//     category: "APAC",
//     categoryId: 1,
//     children: [
//       // { name: "TM", code: 0 },
//       // { name: "TJ", code: 0 },
//       // { name: "KG", code: 0 },
//       // { name: "KZ", code: 0 },
//       // { name: "UZ", code: 0 },
//       { name: "CN", code: 0 },
//       { name: "HK", code: 0 },
//       { name: "JP", code: 0 },
//       // { name: "KP", code: 0 },
//       { name: "KR", code: 0 },
//       // { name: "MN", code: 0 },
//       // { name: "MO", code: 0 },
//       { name: "TW", code: 0 },
//       // { name: "AF", code: 0 },
//       // { name: "BD", code: 0 },
//       // { name: "BT", code: 0 },
//       { name: "IN", code: 0 },
//       // { name: "IR", code: 0 },
//       // { name: "LK", code: 0 },
//       // { name: "MV", code: 0 },
//       // { name: "NP", code: 0 },
//       // { name: "PK", code: 0 },
//       // { name: "BN", code: 0 },
//       // { name: "ID", code: 0 },
//       // { name: "KH", code: 0 },
//       // { name: "LA", code: 0 },
//       // { name: "MM", code: 0 },
//       // { name: "BU", code: 0 },
//       // { name: "MY", code: 0 },
//       // { name: "PH", code: 0 },
//       { name: "SG", code: 0 },
//       // { name: "TH", code: 0 },
//       // { name: "TL", code: 0 },
//       // { name: "TP", code: 0 },
//       // { name: "VN", code: 0 },
//       // { name: "AE", code: 0 },
//       // { name: "AM", code: 0 },
//       // { name: "AZ", code: 0 },
//       // { name: "BH", code: 0 },
//       // { name: "CY", code: 0 },
//       // { name: "GE", code: 0 },
//       { name: "IL", code: 0 },
//       // { name: "IQ", code: 0 },
//       // { name: "JO", code: 0 },
//       // { name: "KW", code: 0 },
//       // { name: "LB", code: 0 },
//       // { name: "OM", code: 0 },
//       // { name: "PS", code: 0 },
//       // { name: "QA", code: 0 },
//       // { name: "SA", code: 0 },
//       // { name: "NT", code: 0 },
//       // { name: "SY", code: 0 },
//       { name: "TR", code: 0 },
//       // { name: "YE", code: 0 },
//       // { name: "YD", code: 0 },
//     ],
//   },
//   {
//     name: "Oceania",
//     code: "009",
//     category: "APAC",
//     categoryId: 1,
//     children: [
//       // { name: "AU", code: 0 },
//       // { name: "NF", code: 0 },
//       // { name: "NZ", code: 0 },
//       // { name: "FJ", code: 0 },
//       // { name: "NC", code: 0 },
//       // { name: "PG", code: 0 },
//       // { name: "SB", code: 0 },
//       // { name: "VU", code: 0 },
//       // { name: "FM", code: 0 },
//       // { name: "GU", code: 0 },
//       // { name: "KI", code: 0 },
//       // { name: "MH", code: 0 },
//       // { name: "MP", code: 0 },
//       // { name: "NR", code: 0 },
//       // { name: "PW", code: 0 },
//       // { name: "AS", code: 0 },
//       // { name: "CK", code: 0 },
//       // { name: "NU", code: 0 },
//       // { name: "PF", code: 0 },
//       // { name: "PN", code: 0 },
//       // { name: "TK", code: 0 },
//       // { name: "TO", code: 0 },
//       // { name: "TV", code: 0 },
//       // { name: "WF", code: 0 },
//       // { name: "WS", code: 0 },
//     ],
//   },
// ];
